package realworld_backend.commerce.event;

// Business-level normalized webhook event types.
public enum BusinessEventType {
    // Checkout session events (mode split happens in CheckoutSessionWebhookService)
    CHECKOUT_SESSION_COMPLETED,
    CHECKOUT_SESSION_ASYNC_PAYMENT_FAILED,
    CHECKOUT_SESSION_EXPIRED,

    // One-time order payment events
    ORDER_PAYMENT_COMPLETED,
    ORDER_PAYMENT_FAILED,
    ORDER_PAYMENT_PENDING,
    ORDER_PAYMENT_EXPIRED,
    ORDER_PAYMENT,

    // Subscription lifecycle events
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_DELETED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_PAYMENT_FAILED,
    SUBSCRIPTION_TRIAL_ENDING,
    SUBSCRIPTION_PAUSED,
    SUBSCRIPTION_RESUMED,
    SUBSCRIPTION,

    // Other commerce events
    PAYMENT_ACTION_REQUIRED,
    REFUND_PROCESSED,
    REFUND_SUCCEEDED,
    INVOICE_PAID,
    INVOICE_PAYMENT_FAILED,
    INVOICE_PAYMENT_SUCCEEDED,
    INVOICE,
    CUSTOMER_SUBSCRIPTION_TRIAL_WILL_END,
    SUBSCRIPTION_HISTORY_MISSING,
    SUBSCRIPTION_UPDATE_FAIL,
    SUBSCRIPTION_MISSING,
    CUSTOMER_SUBSCRIPTION_MISSING,
    UNKNOWN_EVENT
}

